//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamgooEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DamgooEntities : DbContext
    {
        public DamgooEntities()
            : base("name=DamgooEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaracteristicProduit> CaracteristicProduit { get; set; }
        public virtual DbSet<CategoryProduit> CategoryProduit { get; set; }
        public virtual DbSet<ColorProduit> ColorProduit { get; set; }
        public virtual DbSet<Entrepot> Entrepot { get; set; }
        public virtual DbSet<GenreProduit> GenreProduit { get; set; }
        public virtual DbSet<Mouvement> Mouvement { get; set; }
        public virtual DbSet<NatureProduit> NatureProduit { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<SupplierProduit> SupplierProduit { get; set; }
        public virtual DbSet<TypeProduit> TypeProduit { get; set; }
    }
}
