//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamgooEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouvement
    {
        public string produitID { get; set; }
        public Nullable<int> entrepotID { get; set; }
        public Nullable<double> QteMvt { get; set; }
        public Nullable<bool> TypeMvt { get; set; }
        public Nullable<System.DateTime> DateMvt { get; set; }
        public Nullable<double> QteGlobal { get; set; }
        public Nullable<double> QteGlobalPrix { get; set; }
        public Nullable<decimal> PrixMvt { get; set; }
        public int mvtID { get; set; }
    
        public virtual Entrepot Entrepot { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
