//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamgooEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Mouvement = new HashSet<Mouvement>();
        }
    
        public string produitID { get; set; }
        public string libelle { get; set; }
        public Nullable<decimal> PrixActuel { get; set; }
        public Nullable<double> QteGlobal { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> NatureID { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CaracteristicID { get; set; }
    
        public virtual CaracteristicProduit CaracteristicProduit { get; set; }
        public virtual CategoryProduit CategoryProduit { get; set; }
        public virtual ColorProduit ColorProduit { get; set; }
        public virtual GenreProduit GenreProduit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mouvement> Mouvement { get; set; }
        public virtual NatureProduit NatureProduit { get; set; }
        public virtual SupplierProduit SupplierProduit { get; set; }
        public virtual TypeProduit TypeProduit { get; set; }
    }
}
